name: build_smart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.2
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  fonts:
    - family: noah-regular
      fonts:
        - asset: assets/fonts/noah-regular.otf

    - family: BuildSmartIcons
      fonts:
        - asset: assets/fonts/BuildSmartIcons.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  color: "#0716ed"
  image: assets/images/logo.png
  android: true
  ios: true
